# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

format = """
[╭](rosewater) $directory$git_branch$git_status$nodejs${custom.typescript}${custom.turbo}${custom.env}$docker_context$python$cmd_duration$time
$character"""

# Starship modules
[character]
# Note the use of Catppuccin color 'peach'
format = "[╰─](rosewater) "
# success_symbol = "[❯](green)"
# error_symbol = "[❯](red)"
# success_symbol = "[[󰄛](green) ❯](peach)"
# error_symbol = "[[󰄛](red) ❯](peach)"

[directory]
read_only = " 󰌾"
style = "bold lavender"
truncate_to_repo = true
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
style = "bold mauve"
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
style = "bold peach"
format = "[$all_status$ahead_behind]($style) "
conflicted = "⚠"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
stashed = "\\$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[docker_context]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[deno]
symbol = " "

[golang]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[swift]
symbol = " "

[zig]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
